SigmaGradPhi
aurora-multiphysics/hephaestus pull request #59
Opened 2024-01-15 16:33 UTC by Heinrich-BR

This is a cleaner and segfault-free implementation of the conductivity coefficient changes for the ClosedCoilSolver with some name changes for variables related to the gradient of the scalar field within ScalarPotentialSource, OpenCoilSolver, and ClosedCoilSolver.

2024-01-16 13:05 UTC, alexanderianblair requested changes
Looks like this is currently missing any test checking that inhomogeneous conductivities result in the correct current distribution when plugged into `OpenCoilSolver` or `ClosedCoilSolver`.

Could also benefit from a few extra comments defining the E field in terms of GradPotential (and thus the choice of sign of this potential w.r.t. the usual electric potential).

2024-01-16 13:48 UTC, Heinrich-BR commented on examples/closed_coil/Main.cpp
> +zeroVec(const mfem::Vector & x, mfem::Vector & V)
This was just something that remained from my tests with boundary conditions. I've removed it now

2024-01-16 13:49 UTC, Heinrich-BR commented on examples/closed_coil/Main.cpp
> +      "electrical_conductivity", new mfem::FunctionCoefficient(sigmafunc), true);
That's fair enough, Just changed that

2024-01-16 13:53 UTC, Heinrich-BR commented on test/unit/test_opencoil.cpp
> +  ocs_params.SetParam("GradPotentialName", std::string("E"));
Cool, I'll create one!

2024-01-16 13:54 UTC, Heinrich-BR commented on src/sources/open_coil.hpp
> +  mfem::ParGridFunction * grad_p_t_parent_;
Done

2024-01-16 13:56 UTC, Heinrich-BR commented on examples/open_coil/Main.cpp
> +  coefficients.scalars.Register(
I've set it to be a constant coefficient. I've also renames zeroVec in this case to be a constVec, to remove any confusion the name might cause

2024-01-16 15:02 UTC, Heinrich-BR commented on src/sources/closed_coil.hpp
> +  // Seting grad_phi_transfer_ to true will negatively affect performance, but
I've expanded the comment to discuss the definition of grad_phi and the equation being solved

2024-01-16 16:54 UTC, Heinrich-BR commented on test/unit/test_opencoil.cpp
> +  ocs_params.SetParam("GradPotentialName", std::string("E"));
Done!

2024-01-18 12:01 UTC, alexanderianblair approved these changes
Thanks - addition of the test for an open coil of inhomogeneous conductivity is particularly useful!

2024-01-18 12:05 UTC, merged